---
- name: Converge
  hosts: all
  connection: local
  become: true
  gather_facts: true
  
  # РЕШЕНИЕ: Объявляем переменные, которые ожидает ваша роль
  vars:
    db_version: "15"
    db_user: "devops"
    db_name: "prod"
    db_password: "qwe123qwe"

  tasks:
    - name: Запустить задачи роли PostgreSQL
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/../../tasks/main.yml"
